name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-build-download:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: build/test-results/test

    - name: Upload HTML test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: junit-html-report
        path: build/reports/tests/test

    - name: Deploy HTML test report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/reports/tests/test
        publish_branch: gh-pages
        commit_message: "Deploy test report from GitHub Actions"

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: springbootstudy-jar
        path: build/libs/*.jar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
